baseURL = "/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "github.com/themefisher/twenty-twenty-hugo"
title = "Ayush Kumar"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "sample-page"
name = "Sample Page"
weight = 5
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Ayush Kumar"
description = "Thoughts, Musings, Stories and Ideas."
[params.banner]
heading = "Ayush Kumar"
image = ""
[params.blog]
heading = "Articles"
[params.call_to_action]
button_label = ""
button_url = ""
content = ""
enable = false
title = ""
[params.footer]
address = ""
content = ""
copyright = "Copyright &copy; 2022 Ayush Kumar"
hours = ""
title = ""
[params.gallery]
enable = false
gallery_item = []
[params.social]
email = "ayushkumarpage@pm.me"
facebook = "https://facebook.com/ayushkumarpage"
instagram = "https://instagram.com/ayushkumarpage"
linkedin = "https://linkedin.com/in/ayushkumarpage"
twitter = "https://twitter.com/ayushkumarpage"
yelp = "https://yelp.com/ayushkumarpage"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
